#!/usr/bin/env groovy

pipeline {
  agent { label 'jnlp-docker01' }
  environment {
    DOCKER_IMAGE = "demo"
    SOURCE_REPO = "sbc-docker-candidates"
    TARGET_REPO = "sbc-docker-releases"
    tag_name = "${Calendar.getInstance()format('yyyyMMddHHmmss')}"
    latest_tag_name = "latest"
    EXTRA_BUILD_ARGS = "--no-cache"
    BUILDID = "${env.BUILD_ID}"
    SRC_DIR = "docker_env"
  }
  triggers {
    gerrit(customUrl: '',
      gerritProjects: [[
        branches: [[
          compareType: 'PLAIN',
          pattern: 'A7510_S190_Integration'
        ]],
        compareType: 'PLAIN',
        disableStrictForbiddenFileVerification: false,
        pattern: 'gw/scripts/jenkins'
      ]],
      serverName: 'nokia-gerrit',
      triggerOnEvents: [
        changeMerged(),
        patchsetCreated(
          excludeDrafts: true,
          excludeNoCodeChange: false,
          excludeTrivialRebase: false
        )
      ]
    )
  }
  options {
    disableConcurrentBuilds()
    timeout(time: 2, unit: 'DAYS')
    buildDiscarder(logRotator(daysToKeepStr: '7', artifactDaysToKeepStr: '0'))
    timestamps()
  }
  stages {
    stage('build') {
      steps {
          sh '''
	 	pwd
		cd $SRC_DIR
		docker build $EXTRA_BUILD_ARGS -t $DOCKER_IMAGE-$BUILDID .
		sleep 10
	    '''
      }
    }


  }

}



