#!/usr/bin/env groovy



pipeline {
		agent {
			docker {
				image '135.251.149.68:5000/mgw_build:latest'
				args '--rm  --cpus 6 -v /var/run/docker.sock:/var/run/docker.sock -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock -v /root/.ssh/:/root/.ssh/ -v /home/jenkins/:/home/jenkins/ -v /viewstores/third-party/:/viewstores/third-party/ -v /tmp/:/tmp/ -v /var/tmp/:/var/tmp/'

			}
		}
    stages {
        stage('Example') {
            steps {
                echo 'Hello World'

                script {
                    def browsers = ['chrome', 'firefox']
                    for (int i = 0; i < browsers.size(); ++i) {
                        echo "Testing the ${browsers[i]} browser"
                    }
                }
            }
        }
    }
}