#!/usr/bin/env groovy

pipeline {
	agent {
		docker {
			image 'demo-6'
			args '  --privileged --init --cpus 6 -v /var/run/docker.sock:/var/run/docker.sock -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock -v /root/.ssh/:/root/.ssh/ -v /home/jenkins/:/home/jenkins/ -v /viewstores/third-party/:/viewstores/third-party/ -v /tmp/:/tmp/ -v /var/tmp/:/var/tmp/'


		}
	}
    stages {
        stage('Example') {
            steps {
		sh 'sleep 10'
                echo 'Hello World'
		sh 'env'
		sh 'sleep 10'
		
                script {
                    def browsers = ['chrome']
                    for (int i = 0; i < browsers.size(); ++i) {
                        echo "Testing the ${browsers[i]} browser"
		   }
                }
		sleep 210
            }
        }
    }
}
